# Initialize
init:
	pip install -r requirements.txt

# Create a new environment
env:
	conda create -n qa_dataset python=3.10
	conda activate qa_dataset
	pip install -r requirements.txt

# Generate questions from pdf files
generate:
	bash scripts/generate.sh $(args)

generate_one_file:
	bash scripts/generate_one_file.sh

merge:
	bash scripts/merge.sh

evaluate:
	bash scripts/evaluate.sh